apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  serviceName: "prometheus"
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      containers:
      - name: prometheus
        image: prom/prometheus:v1.7.0
        args:
        - -config.file=/etc/monitoring/prometheus.yml
        - -storage.local.path=/prometheus
        - -storage.local.retention=24h
        - -storage.local.target-heap-size=2147483648
        - -alertmanager.url=http://alertmanager
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 3000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: data
          mountPath: /prometheus
        - name: monitoring-config
          mountPath: /etc/monitoring
      volumes:
      - name: monitoring-config
        configMap:
          name: monitoring-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
