apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "new-chart.full_name" . }}
  labels:
    {{- include "new-chart.release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "new-chart.release_labels" . | indent 8 }}
    spec:
      containers:
        - name: new-chart-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
              protocol: TCP
